### ISSUE TITLE
dask raisies exception

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#183]
When I run on OSX following the instructions on the homepage, the logs show the following dask exceptions:

```Traceback (most recent call last):
  File "/anaconda2/envs/skyportal/bin/dask-scheduler", line 7, in <module>
    from distributed.cli.dask_scheduler import go
  File "/anaconda2/envs/skyportal/lib/python3.6/site-packages/distributed/__init__.py", line 3, in <module>
Traceback (most recent call last):
    from . import config
  File "/anaconda2/envs/skyportal/bin/dask-worker", line 7, in <module>
  File "/anaconda2/envs/skyportal/lib/python3.6/site-packages/distributed/config.py", line 13, in <module>
    from distributed.cli.dask_worker import go
  File "/anaconda2/envs/skyportal/lib/python3.6/site-packages/distributed/__init__.py", line 3, in <module>
    from . import config
    config = dask.config.config
AttributeError: module 'dask' has no attribute 'config'
  File "/anaconda2/envs/skyportal/lib/python3.6/site-packages/distributed/config.py", line 13, in <module>
    config = dask.config.config
AttributeError: module 'dask' has no attribute 'config'```

**Comment by dannygoldstein** [comment]
```(skyportal) Dannys-MBP:skyportal danny$ conda list
# packages in environment at /anaconda2/envs/skyportal:
#
# Name                    Version                   Build  Channel
anyjson                   0.3.3                 py36_1001    conda-forge
apispec                   1.3.3                      py_0    conda-forge
aplpy                     1.1.1                    py36_1    conda-forge
argon2_cffi               19.1.0          py36h1de35cc_1000    conda-forge
arrow                     0.13.0                   pypi_0    pypi
asn1crypto                0.24.0                py36_1003    conda-forge
astropy                   3.0.3                    py36_1    conda-forge
astroquery                0.3.8                   py_1000    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
avro-python3              1.8.2                    pypi_0    pypi
babel                     2.7.0                      py_0    conda-forge
bcrypt                    3.1.6            py36h01d97ff_1    conda-forge
beautifulsoup4            4.7.1                 py36_1001    conda-forge
bokeh                     0.12.9                   py36_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
cffi                      1.12.3           py36hccf1714_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.1                      py_0    conda-forge
colour                    0.1.5                      py_0    conda-forge
cryptography              2.7              py36h212c5bf_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1         py36h1de35cc_1001    conda-forge
dask                      0.15.1                   py36_0    conda-forge
dask-core                 1.2.2                      py_0    conda-forge
defusedxml                0.6.0                    pypi_0    pypi
distributed               1.28.1                   py36_0    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
factory-boy               2.11.1                   pypi_0    pypi
faker                     1.0.7                    pypi_0    pypi
fastavro                  0.21.7                   pypi_0    pypi
freetype                  2.8.1                hfa320df_1    conda-forge
furl                      1.0.1                    py36_0    conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
idna                      2.8                   py36_1000    conda-forge
importlib_metadata        0.18                     py36_0    conda-forge
infinity                  1.4                        py_0    conda-forge
intervals                 0.8.1                      py_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
joblib                    0.13.2                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
keyring                   19.0.2                   py36_0    conda-forge
kiwisolver                1.1.0            py36h770b8ee_0    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libcxx                    8.0.0                         2    conda-forge
libcxxabi                 8.0.0                         2    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               3.0.1                         0    conda-forge
liblapack                 3.8.0                7_openblas    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libtiff                   4.0.10            hd08fb8f_1003    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
markupsafe                1.1.1            py36h1de35cc_0    conda-forge
marshmallow               3.0.0rc5                   py_0    conda-forge
marshmallow-enum          1.4.1                    py36_0    conda-forge
marshmallow-sqlalchemy    0.16.4                     py_0    conda-forge
matplotlib                2.1.0            py36h5068139_0
more-itertools            4.3.0                 py36_1000    conda-forge
msgpack-python            0.6.1            py36h04f5b5a_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.16.4           py36h6b0580a_0    conda-forge
oauthlib                  3.0.1                    pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.5             h436c29b_1001    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
orderedmultidict          0.7.11                   py36_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.2           py36h86efe34_0    conda-forge
partd                     0.3.10                     py_1    conda-forge
passlib                   1.7.1                      py_0    conda-forge
phonenumbers              8.10.10                    py_0    conda-forge
pillow                    5.2.0            py36h2dc6135_1    conda-forge
pip                       19.1.1                   py36_0    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
psutil                    5.6.3            py36h01d97ff_0    conda-forge
psycopg2-binary           2.7.3.2                  pypi_0    pypi
py                        1.8.0                      py_0    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pyjwt                     1.7.1                    pypi_0    pypi
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pysocks                   1.7.0                    py36_0    conda-forge
pytest                    4.3.1                    pypi_0    pypi
pytest-arraydiff          0.3                        py_0    conda-forge
pytest-astropy            0.5.0                      py_0    conda-forge
pytest-doctestplus        0.3.0                      py_0    conda-forge
pytest-openfiles          0.3.1                      py_0    conda-forge
pytest-randomly           2.1.1                    pypi_0    pypi
pytest-remotedata         0.3.1                      py_0    conda-forge
python                    3.6.7             h8dc6b48_1004    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python3-openid            3.1.0                    pypi_0    pypi
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1.1            py36h01d97ff_0    conda-forge
pyzmq                     18.0.1                   pypi_0    pypi
readline                  7.0               hcfe32e1_1001    conda-forge
requests                  2.22.0                   py36_0    conda-forge
requests-file             1.4.3                    pypi_0    pypi
requests-oauthlib         1.2.0                    pypi_0    pypi
scipy                     1.3.0            py36hab3da7d_0    conda-forge
selenium                  3.141.0                  pypi_0    pypi
selenium-requests         1.3                      pypi_0    pypi
setuptools                41.0.1                   py36_0    conda-forge
simplejson                3.16.0                   pypi_0    pypi
six                       1.12.0                py36_1000    conda-forge
social-auth-app-tornado   1.0.0                    pypi_0    pypi
social-auth-core          3.2.0                    pypi_0    pypi
social-auth-storage-sqlalchemy 1.1.0                    pypi_0    pypi
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.9.1                    py36_0    conda-forge
sqlalchemy                1.2.18                   pypi_0    pypi
sqlalchemy-utils          0.34.0                     py_0    conda-forge
sqlite                    3.28.0               h9721f7c_0    conda-forge
tblib                     1.4.0                      py_0    conda-forge
text-unidecode            1.2                      pypi_0    pypi
tk                        8.6.9             h2573ce8_1002    conda-forge
tldextract                2.2.1                    pypi_0    pypi
toolz                     0.9.0                      py_1    conda-forge
tornado                   4.5.3                    pypi_0    pypi
tqdm                      4.23.2                     py_0    conda-forge
urllib3                   1.24.3                   py36_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.4                   py36_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zict                      0.1.4                      py_0    conda-forge
zipp                      0.5.1                      py_0    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
zstd                      1.4.0                ha9f0a20_0    conda-forge

**Comment by stefanv** [comment]
Temporary workaround: disable dask by removing the last two sections of `baselayer/conf/supervisor/supervisor.conf.template`/
