### ISSUE TITLE
redshift_history.append AttributeError: 'str' object has no attribute 'append'

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#1904]
Issuing the command

```
out=requests.request('POST','http://desi2.lbl.gov:5000/api/candidates',
                      json={'ra': 194.74739749688365, 'dec': 26.984488611157552, 'id': 'DESI39628417150225913', 'filter_ids': [17], 'passing_alert_id': 17, 'passed_at': '2021-04-22', 'altdata': {'fibermap': {'FIBER': '156', 'TILEID': '123', 'PETAL_LOC': '0', 'LAST_MJD': '59323.273'}, 'classifier': {'CNNLABEL': 'SN IIP'}}, 'redshift': 0.33975055552605876, 'redshift_history': 'Redrock'},
                      headers = {'Authorization': 'token xxxxx'})
```

I get the error
```
ERROR:tornado.application:Uncaught exception POST /api/candidates (127.0.0.1)
HTTPServerRequest(protocol='http', host='desi2.lbl.gov:5000', method='POST', uri='/api/candidates', version='HTTP/1.0', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/akim/miniconda3/lib/python3.8/site-packages/tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/akim/skyportal/baselayer/app/access.py", line 30, in wrapper
    return method(self, *args, **kwargs)
  File "/home/akim/skyportal/baselayer/app/access.py", line 51, in wrapper
    return method(self, *args, **kwargs)
  File "/home/akim/skyportal/skyportal/handlers/api/candidate.py", line 940, in post
    update_redshift_history_if_relevant(data, obj, self.associated_user_object)
  File "/home/akim/skyportal/skyportal/handlers/api/candidate.py", line 39, in update_redshift_history_if_relevant
    redshift_history.append(
AttributeError: 'str' object has no attribute 'append'
```

**Comment by AlexGKim** [comment]
Got it.
