### ISSUE TITLE
crash in creating an administrative user

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#208]
I get the following error when trying to add as administrative user.

> (skyportal_env) skyportal@7add75822429:/skyportal$ python
Python 3.6.8 (default, May  8 2019, 05:35:00) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from skyportal.model_util import add_super_user
>>> add_super_user('testuser@cesium-ml.org')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/skyportal/skyportal/model_util.py", line 19, in add_super_user
    setup_permissions()  # make sure permissions already exist
  File "/skyportal/skyportal/model_util.py", line 39, in setup_permissions
    all_acls = [ACL.create_or_get(a) for a in all_acl_ids]
  File "/skyportal/skyportal/model_util.py", line 39, in <listcomp>
    all_acls = [ACL.create_or_get(a) for a in all_acl_ids]
  File "/skyportal/baselayer/app/models.py", line 69, in create_or_get
    obj = cls.query.get(id)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 936, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1026, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 282, in load_on_pk_identity
    return q.one()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3039, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3008, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3081, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3103, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3111, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3096, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1115, in connection
    bind = self.get_bind(mapper, clause=clause, **kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1531, in get_bind
    % (", ".join(context))
sqlalchemy.exc.UnboundExecutionError: Could not locate a bind configured on mapper Mapper|ACL|acls, SQL expression or this Session

**Comment by acrellin** [comment]
Hi @AlexGKim 
The error you're seeing is due to the fact that you haven't created a DB connection before trying to modify the DB.  Please see this section of the docs for instructions on manually setting up a DB connection in the terminal: https://skyportal.io/docs/dev.html?highlight=init_db#database

Please let us know if you have any further questions.

Thanks!
