### ISSUE TITLE
Photometry plot failure

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3163]
Traceback (most recent call last):
  File "/skyportal_env/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/skyportal/baselayer/app/access.py", line 56, in wrapper
    return tornado.web.authenticated(method)(self, *args, **kwargs)
  File "/skyportal_env/lib/python3.8/site-packages/tornado/web.py", line 3173, in wrapper
    return method(self, *args, **kwargs)
  File "/skyportal/skyportal/handlers/api/internal/plot.py", line 40, in get
    self.success(data={'bokehJSON': json, 'url': self.request.uri})
  File "/skyportal/skyportal/handlers/base.py", line 18, in success
    super().success(*args, **kwargs, extra={'version': __version__})
  File "/skyportal/baselayer/app/handlers/base.py", line 355, in success
    self.write(to_json({"status": "success", "data": data, **extra}))
  File "/skyportal/baselayer/app/json_util.py", line 53, in to_json
    return json.dumps(obj, cls=Encoder, indent=2, ignore_nan=True)
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/__init__.py", line 398, in dumps
    return cls(
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 298, in encode
    chunks = list(chunks) 
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 704, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 658, in _iterencode_dict
    for chunk in chunks:
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 658, in _iterencode_dict
    for chunk in chunks:
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 724, in _iterencode
    o = _default(o) 
  File "/skyportal/baselayer/app/json_util.py", line 49, in default
    return json.JSONEncoder.default(self, o)
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 272, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type Tabs is not JSON serializable

PHOTOMETRY PLOT FAILED ON THIS DATASET
          id                 created_at                   modified  ra  dec  \
0  190747966 2022-01-23 23:32:23.251651 2022-01-23 23:32:23.251651 NaN  NaN
2  144262674 2021-08-03 15:56:47.532767 2021-08-03 15:56:47.532767 NaN  NaN
1  190747967 2022-01-23 23:33:25.021433 2022-01-23 23:33:25.021433 NaN  NaN
3  144262675 2021-08-03 15:57:51.258325 2021-08-03 15:57:51.258325 NaN  NaN

            mjd  flux    fluxerr filter  ra_unc  dec_unc altdata  \
0  59426.712873   NaN   6.551441  sdssr     NaN      NaN    None
2  59426.712873   NaN   6.551468  sdssr     NaN      NaN    None
1  59426.723957   NaN  21.193320  sdssi     NaN      NaN    None
3  59426.723957   NaN  21.190503  sdssi     NaN      NaN    None

                              upload_id origin        obj_id  instrument_id  \
0  203c47fe-b2ec-4a51-955d-f843120aa674   None  ZTF20ablkuio             66
2  6e778eb9-e9cf-46ba-bc6c-2c529e0a1b91   None  ZTF20ablkuio             66
1  732e537e-5d41-4588-9ce6-afc2cf5c4e7c   None  ZTF20ablkuio             66
3  7ec295db-2e87-4094-9eb4-e74b013167ba   None  ZTF20ablkuio             66

  followup_request_id assignment_id  owner_id telescope instrument  \
0                None          None        27   LCOGT2m   Spectral
2                None          None        27   LCOGT2m   Spectral
1                None          None        27   LCOGT2m   Spectral
3                None          None        27   LCOGT2m   Spectral

       effwave   color           label    zp magsys  alpha    lim_mag  \
0  6186.798255     red  Spectral/sdssr  23.9     ab    1.0  20.666355
2  6186.798255     red  Spectral/sdssr  23.9     ab    1.0  20.666350
1  7506.207753  orange  Spectral/sdssi  23.9     ab    1.0  19.391699
3  7506.207753  orange  Spectral/sdssi  23.9     ab    1.0  19.391844

   hasflux  mag  magerr    obs  stacked
0    False  NaN     NaN  False    False
2    False  NaN     NaN  False    False
1    False  NaN     NaN  False    False
3    False  NaN     NaN  False    False

**Comment by guynir42** [comment]
@mcoughlin add a test that recreates this bug and then fix the bug.

**Comment by jadalilleboe** [comment]
@mcoughlin so is this bad data or is there a bug with the photometry plot code? Anyhow, the "TypeError: Object of type Tabs is not JSON serializable" error should be caught and a more useful error message should be displayed to the user I would think. This source has the same error and the photometry plot looks like it's loading even though there was an error: [https://fritz.science/source/ZTF22aayhytz](https://fritz.science/source/ZTF22aayhytz)

**Comment by mcoughlin** [comment]
@jadalilleboe i guess it's bad but technically allowed, so good if we can capture the error for sure.
