### ISSUE TITLE
Telescope return failure

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3164]
2022-07-01 10:20:03,667 - tornado.application - ERROR - Uncaught exception GET /api/telescope (130.237.240.55)
HTTPServerRequest(protocol='http', host='fritz.science', method='GET', uri='/api/telescope', version='HTTP/1.0', remote_ip='130.237.240.55')
Traceback (most recent call last):
  File "/skyportal_env/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/skyportal/baselayer/app/access.py", line 56, in wrapper
    return tornado.web.authenticated(method)(self, *args, **kwargs)
  File "/skyportal_env/lib/python3.8/site-packages/tornado/web.py", line 3173, in wrapper
    return method(self, *args, **kwargs)
  File "/skyportal/skyportal/handlers/api/telescope.py", line 166, in get
    return self.success(data=telescopes)
  File "/skyportal/skyportal/handlers/base.py", line 18, in success
    super().success(*args, **kwargs, extra={'version': __version__})
  File "/skyportal/baselayer/app/handlers/base.py", line 355, in success
    self.write(to_json({"status": "success", "data": data, **extra}))
  File "/skyportal/baselayer/app/json_util.py", line 53, in to_json
    return json.dumps(obj, cls=Encoder, indent=2, ignore_nan=True)
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/__init__.py", line 398, in dumps
    return cls(
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 298, in encode
    chunks = list(chunks)
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 704, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 658, in _iterencode_dict
    for chunk in chunks:
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 534, in _iterencode_list
    for chunk in chunks:
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 658, in _iterencode_dict
    for chunk in chunks:
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 724, in _iterencode
    o = _default(o)
  File "/skyportal/baselayer/app/json_util.py", line 49, in default
    return json.JSONEncoder.default(self, o)
  File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 272, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type Time is not JSON serializable

**Comment by Theodlz** [comment]
Hi Michael, any details in the logs as to where something went wrong in the handler, or is it just in the return ?. Maybe we should add some extra try catch in the baselayer methods that take care of that (in the base handler maybe) rather than in the telescope handler ?

**Comment by mcoughlin** [comment]
@Theodlz This is unfortunately all I see! We could also in the telescopes return first send it to dictionary and check serialization of that to avoid baselayer?

**Comment by Theodlz** [comment]
What I see here at the end of the logs is that it can't serialize an object of type time. Maybe what we should do is check that everything can be parsed as a string, which is what is needed to send data back as an api response I believe.

**Comment by mcoughlin** [comment]
Yes I guess I was suggesting before the self.success(data=) call to try a json.dumps() on a data=[t.to_dict() for t in telescopes] type thing.

**Comment by Theodlz** [comment]
Sounds good, and maybe this should be done in other handlers too.
