### ISSUE TITLE
GCN event ingestion: Error generating localizations

### ISSUE THREAD

**Issue by Theodlz** [skyportal/skyportal#3867]
Running SP locally, I noticed that an error occurs when ingesting some events (not all of them, just a few). I get:
```
Traceback (most recent call last):
  File "/home/theodlz/alright/shift_management_admin_menu/skyportal/services/gcn_service/gcn_service.py", line 81, in <module>
    raise e
  File "/home/theodlz/alright/shift_management_admin_menu/skyportal/services/gcn_service/gcn_service.py", line 78, in <module>
    service()
  File "/home/theodlz/alright/shift_management_admin_menu/skyportal/services/gcn_service/gcn_service.py", line 73, in service
    raise e
  File "/home/theodlz/alright/shift_management_admin_menu/skyportal/services/gcn_service/gcn_service.py", line 69, in service
    post_gcnevent_from_xml(payload, user_id, session)
  File "/home/theodlz/alright/shift_management_admin_menu/skyportal/skyportal/handlers/api/gcn.py", line 246, in post_gcnevent_from_xml
    add_tiles_and_properties_and_observation_plans(
  File "/home/theodlz/alright/shift_management_admin_menu/skyportal/skyportal/handlers/api/gcn.py", line 1291, in add_tiles_and_properties_and_observation_plans
    raise e
  File "/home/theodlz/alright/shift_management_admin_menu/skyportal/skyportal/handlers/api/gcn.py", line 1140, in add_tiles_and_properties_and_observation_plans
    properties_dict, tags_list = get_skymap_properties(localization)
  File "/home/theodlz/alright/shift_management_admin_menu/skyportal/skyportal/utils/gcn.py", line 491, in get_skymap_properties
    result = ligo.skymap.postprocess.crossmatch(sky_map, contours=(0.9,), areas=(500,))
  File "/home/theodlz/alright/shift_management_admin_menu/skyportal/env/lib/python3.10/site-packages/ligo/skymap/postprocess/crossmatch.py", line 346, in crossmatch
    contour_idxs = np.digitize(contours, prob) - 1
  File "<__array_function__ internals>", line 180, in digitize
  File "/home/theodlz/alright/shift_management_admin_menu/skyportal/env/lib/python3.10/site-packages/numpy/lib/function_base.py", line 5551, in digitize
    raise ValueError("bins must be monotonically increasing or decreasing")
ValueError: bins must be monotonically increasing or decreasing
```

meaning that the `prob` variable (passed to digitize as `bins`) is not monotonous. Some values might repeat themselves or aren't ordered. I am not sure that this should be an issue, but the digitize method from NumPy treats it as is.

Unfortunately (or fortunately!) errors are all caught and we have minimal insight over what could have gone wrong, or at least where in the code. I strongly suggest whoever will try to fix this to raise the error where it is simply logged for now in the `post_gcnevent_from_xml` method, and then raise it again in the try/except at the bottom of the gcn service.

**Comment by Theodlz** [comment]
For testing purposes here is a skymap that caused a failure: 
https://heasarc.gsfc.nasa.gov/FTP/fermi/data/gbm/triggers/2023/bn230118996/quicklook/glg_healpix_all_bn230118996.fit

It came from a `NoticeType.FERMI_GBM_FIN_POS` event

**Comment by mcoughlin** [comment]
@lpsinger We have an example of a skymap that ligo.skymap struggles with for computing statistics on.

**Comment by lpsinger** [comment]
OK. I'll take a look at it tonight.

**Comment by mcoughlin** [comment]
@lpsinger identified this as being due to problematic IPN maps, that have now been fixed by that team. closing.
