### ISSUE TITLE
Supervisor fails to spin up app much of the time, or its status is not being properly detected in verify_server_availability

### ISSUE THREAD

**Issue by acrellin** [skyportal/skyportal#399]
@stefanv this started happening when we switched from the `apt`-installed supervisor to the `pip`-installed version. Below is a typical error message: 
```
[22:04:16 test_frontend] Waiting for server to appear at http://localhost:5000...
[22:05:43 test_frontend] Could not launch server processes; terminating
Command 'python -m supervisor.supervisorctl -c baselayer/conf/supervisor/supervisor.conf status' returned non-zero exit status 3.
[22:05:43 test_frontend] Terminating supervisord...
make[3]: *** wait: No child processes.  Stop.
make[3]: *** Waiting for unfinished jobs....
make[3]: *** wait: No child processes.  Stop.
Traceback (most recent call last):
  File "./baselayer/tools/test_frontend.py", line 99, in <module>
    verify_server_availability(server_url)
  File "./baselayer/tools/test_frontend.py", line 63, in verify_server_availability
    raise ConnectionError(str(e)) from None
ConnectionError: Command 'python -m supervisor.supervisorctl -c baselayer/conf/supervisor/supervisor.conf status' returned non-zero exit status 3.
Makefile:61: recipe for target 'run_testing' failed
make[2]: *** [run_testing] Error 2
baselayer/Makefile:133: recipe for target 'test' failed
make[1]: *** [test] Error 1
Makefile:61: recipe for target 'test' failed
make: *** [test] Error 2
```

**Comment by acrellin** [comment]
High priority

**Comment by acrellin** [comment]
@stefanv can we simply revert to using the `apt`-installed supervisor while we track down the source of the issue with using the `pip`-installed version?

**Comment by stefanv** [comment]
There are two factors: new supervisor launch mechanism, and switch to supervisor 4. I think it has to do with supervisor 4, not the launch mechanism. They changed the output they provided for the supervisorctl monitor.

**Comment by acrellin** [comment]
It only fails some of the time, though, which indicates that the expected
output is sometimes present.

**Comment by acrellin** [comment]
This has been addressed in recent PRs
