### ISSUE TITLE
OpenAI Embeddings breaking the app

### ISSUE THREAD

**Issue by Theodlz** [skyportal/skyportal#4261]
GitHub actions can't run it seems, because of an error involving openai embeddings:
```
Traceback (most recent call last):
  File "baselayer/services/app/app.py", line 56, in <module>
    app_factory = getattr(importlib.import_module(module), app_factory)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/work/skyportal/skyportal/skyportal/app_server.py", line 9, in <module>
    from skyportal.handlers.api import (
  File "/home/runner/work/skyportal/skyportal/skyportal/handlers/api/__init__.py", line 134, in <module>
    from .summary_query import SummaryQueryHandler
  File "/home/runner/work/skyportal/skyportal/skyportal/handlers/api/summary_query.py", line 5, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/langchain/agents/agent.py", line 17, in <module>
    from langchain.chains.base import Chain
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/langchain/chains/api/base.py", line 8, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/langchain/chains/api/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/langchain/prompts/__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/langchain/prompts/chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/langchain/memory/__init__.py", line 23, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/langchain/memory/vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/langchain/vectorstores/__init__.py", line 2, in <module>
    from langchain.vectorstores.analyticdb import AnalyticDB
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/langchain/vectorstores/analyticdb.py", line 15, in <module>
    from langchain.embeddings.base import Embeddings
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/langchain/embeddings/__init__.py", line 18, in <module>
    from langchain.embeddings.openai import OpenAIEmbeddings
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/langchain/embeddings/openai.py", line 66, in <module>
    class OpenAIEmbeddings(BaseModel, Embeddings):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

**Comment by mcoughlin** [comment]
Pinned some packages and went away ;)
