### ISSUE TITLE
'/skyportal/persistentdata/sncosmo' not an existing directory

### ISSUE THREAD

**Issue by rknop** [skyportal/skyportal#5343]
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
Creating a skyportal instance on a kubernetes cluster from scratch.  Created volume mounts for `/skyportal/persistentdata` and `/skyportal/static/thumbnails` ; both started empty.

Upon starting the skyportal workload, the logs have the following:

```
Traceback (most recent call last):
  File "/skyportal/services/gcn_service/gcn_service.py", line 15, in <module>
    from skyportal.handlers.api.gcn import (
  File "/skyportal/skyportal/handlers/api/__init__.py", line 7, in <module>
    from .analysis import (
  File "/skyportal/skyportal/handlers/api/analysis.py", line 52, in <module>
    from .photometry import serialize
  File "/skyportal/skyportal/handlers/api/photometry.py", line 190, in <module>
    BANDPASSES_COLORS = get_bandpasses_to_colors(ALLOWED_BANDPASSES, "rgb")
  File "/skyportal/skyportal/handlers/api/photometry.py", line 182, in get_bandpasses_to_colors
    return {bandpass: get_color(bandpass, colors_type) for bandpass in bandpasses}
  File "/skyportal/skyportal/handlers/api/photometry.py", line 182, in <dictcomp>
    return {bandpass: get_color(bandpass, colors_type) for bandpass in bandpasses}
  File "/skyportal/skyportal/handlers/api/photometry.py", line 129, in get_color
    wavelength = get_effective_wavelength(bandpass)
  File "/skyportal/skyportal/handlers/api/photometry.py", line 104, in get_effective_wavelength
    bandpass = sncosmo.get_bandpass(bandpass_name, **args)
  File "/skyportal_env/lib/python3.10/site-packages/sncosmo/bandpasses.py", line 27, in get_bandpass
    return _BANDPASSES.retrieve(name)
  File "/skyportal_env/lib/python3.10/site-packages/sncosmo/_registry.py", line 160, in retrieve
    self._instances[key] = func(*args, name=name)
  File "/skyportal_env/lib/python3.10/site-packages/sncosmo/builtins.py", line 75, in load_bandpass_remote_aa
    abspath = DATADIR.abspath(relpath)
  File "/skyportal_env/lib/python3.10/site-packages/sncosmo/utils.py", line 450, in abspath
    abspath = os.path.join(self.rootdir(), relpath)
  File "/skyportal_env/lib/python3.10/site-packages/sncosmo/utils.py", line 415, in rootdir
    raise Exception("data directory {!r} not an existing "
Exception: data directory '/skyportal/persistentdata/sncosmo' not an existing directory
```

**To Reproduce**

1. Create a new skyportal instance including an empty persistentdata directory
2. Search server logs for "not an existing directory"

**Expected behavior**
I'm not sure how much this is going to harm things.  However, I would expect that whatever code is trying to read or write from that directory would check its existence first, and create the directory if it doesn't already exist.

**Platform information:**
Kubernetes cluster using a docker image built from the skyportal Dockerfile, with modifications to docker.yaml for my use case.

- SkyPortal version: 1.0.0 (this github tag)
- Interface: N/A

**Additional context**

**Comment by Theodlz** [comment]
thanks @rknop, looking into it right now

**Comment by Theodlz** [comment]
honestly I feel like sncosmo could create that dir but we can take care of it

**Comment by mcoughlin** [comment]
Moved to skyportal-data.
