### ISSUE TITLE
database error, type 'spectrumtypes' does not exist

### ISSUE THREAD

**Issue by rknop** [skyportal/skyportal#5347]
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
Seeing this was what prompted me to post the `make db_clear` issue I just posted.  After posting that issue, I noticed that there were four processes running at near 100% CPU on the skyportal machine; sometimes python, sometimes alembic.  The `log/app_??.log` (??=00 through 03) are being spammed with output that includes this traceback:

```
Existing tables found; not creating additional tables
Traceback (most recent call last):
  File "/skyportal_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/skyportal_env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedObject: type "spectrumtypes" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/skyportal/baselayer/services/app/app.py", line 58, in <module>
    app = app_factory(
  File "/skyportal/skyportal/app_server.py", line 719, in make_app
    model_util.refresh_enums()
  File "/skyportal/skyportal/model_util.py", line 108, in refresh_enums
    session.execute(
  File "/skyportal_env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/skyportal_env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2133, in _execute_internal
    result = conn.execute(
  File "/skyportal_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/skyportal_env/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 489, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/skyportal_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/skyportal_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/skyportal_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/skyportal_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/skyportal_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/skyportal_env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) type "spectrumtypes" does not exist

[SQL: ALTER TYPE spectrumtypes ADD VALUE IF NOT EXISTS 'source']
(Background on this error at: https://sqlalche.me/e/20/f405)
  Config files: baselayer/config.yaml.defaults
                config.yaml.defaults
                config.yaml
```

It looks like alembic (?) is stuck in some kind of retry/fail loop creating the database.

**To Reproduce**
1. Install skyportal on a containerized environment
2. `make db_init`
3. Look at log/app_00.log, look for the traceback described above.

**Expected behavior**
I wouldn't expect this traceback in the logs, and I would expect alembic to complete the database migration in less than minutes.  After that, with nothing connecting the server, I would not expect high CPU usage.

**Screenshots**

**Platform information:**

- SkyPortal version: v1.0.0 (this github tag)
- Interface
  - [ ] I am using the API
  - [ ] I am browsing on a desktop
  - [ ] I am browsing on a phone
  - [ ] I am browsing on a tablet

**Additional context**
In case it matters, here is the (secret-sensored) `git diff` from `v1.0.0` in the checkout where I created the docker image.  (This same environment applies to the last two issues I submitted.)

```
diff --git a/docker.yaml b/docker.yaml
index 39afc970..1b381001 100644
--- a/docker.yaml
+++ b/docker.yaml
@@ -1,9 +1,33 @@
+app:
+  secret_key: <REDACTED>
+
 database:
-    database: skyportal
-    host: db
-    port: 5432
-    user: skyportal
-    password: password
+  database: skyportal
+  host: postgres
+  port: 5432
+  user: skyportal
+  password: <REDACTED>
 
 server:
-    url: http://localhost:5000
+  protocol: https
+  host: euclid-skyportal.lbl.gov
+  port: 80
+
+  auth:
+    debug_login: False
+    google_oauth2_key: <REDACTED>
+    google_oauth2_secret: <REDACTED>
+
+  rate_limit: 200
+  burst: 1000
+
+invitations:
+  enabled: True
+
+email_service: smtp
+
+smtp:
+  from_email: raknop@lbl.gov
+  password: null
+  host: smtp.lbl.gov
+  port: 25
diff --git a/skyportal/email_utils.py b/skyportal/email_utils.py
index 29ff5b98..4fd11db1 100644
--- a/skyportal/email_utils.py
+++ b/skyportal/email_utils.py
@@ -23,8 +23,9 @@ def send_email(recipients, subject, body):
         sendgrid_client.send(message)
     elif cfg.get("email_service") == "smtp":
         smtp_server = smtplib.SMTP(cfg["smtp.host"], cfg["smtp.port"])
-        smtp_server.starttls()
-        smtp_server.login(cfg["smtp.from_email"], cfg["smtp.password"])
+        if ( cfg["smtp.password"] is not None ) and ( len( cfg["smtp.password"] ) > 0 ):
+            smtp_server.starttls()
+            smtp_server.login(cfg["smtp.from_email"], cfg["smtp.password"])
         msg = MIMEMultipart()
         msg["From"] = cfg["smtp.from_email"]
         msg["To"] = ", ".join(recipients)
```

**Comment by rknop** [comment]
....the problem may be because the container is started with command `make run_production`  (from the Dockerfile), and only after that is started do I run `make db_init`.  I will set it up so that the first time around, it doesn't run `make run_production` before I run` make db_init`, and see if that fixes it.

**Comment by rknop** [comment]
No, this error is still present after running `make db_init` before the first time I run `make run_production`.

**Comment by rknop** [comment]
I see the same behavior on the main branch (commit 8edd03f185311e392a73d7442893f32a710a2a30)

**Comment by Theodlz** [comment]
Maybe the documentation isn't clear enough here but there is a create-table argument that can be passed to create the tables. I'll take a look next week

**Comment by rknop** [comment]
For what it's worth, a whole bunch of tables did get created when I ran `make db_init`

**Comment by Theodlz** [comment]
@rknop for you mean that this error shows up when you start the app after running make db_init? Db init should create users and databases, but tables should be created separately. I'll send you the exact command when I make it to the office.
