### ISSUE TITLE
`make load_seed_data` fails if `make load_demo_data` has already been run 

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#575]
If a user calls `make load_seed_data` after `make load_demo_data` has already been run, they are presented with a low-level error message from SQLAlchemy, complaining that "Sitewide Group" already exists (see below). 

Is this expected behavior? It can be solved by running `make db_clear` before `make load_seed_data`, but not sure if it is intended that the former be required to be run before the latter can run successfully. 

```
(skyportal2) Dannys-MBP:skyportal danny$ make load_seed_data

Welcome to SkyPortal v0.9.dev0+git20200716.c2c9626 (https://skyportal.io)

Checking system dependencies:
[✓] nginx >= 1.7                  [ 1.17.10]
[✓] psql >= 9.6                   [    12.3]
[✓] node (npm) >= 5.8.0           [   6.4.1]
[✓] python >= 3.7                 [   3.7.6]

[✓] Baselayer installed inside of app
--------------------
[✓] Verifying Python package dependencies
[✓] Silently executing: baselayer/tools/check_js_deps.sh
[Baselayer] Missing config files: config.yaml; continuing.

Warning: You are running on the default configuration. To configure your system,
please copy `config.yaml.defaults` to `config.yaml` and modify it as you see fit.

  Config files: baselayer/config.yaml.defaults
                config.yaml.defaults
[✓] Connecting to database skyportal
[·] Creating tablesCreating tables on database skyportal
Refreshed tables:
 - acls
 - roles
 - role_acls
 - users
 - tokens
 - token_acls
 - user_roles
 - usersocialauths
 - nonces
 - associations
 - codes
 - partials
 - groups
 - group_users
 - streams
 - stream_groups
 - objs
 - filters
 - candidates
 - sources
 - sourceviews
 - telescopes
 - group_telescopes
 - instruments
 - taxonomies
 - group_taxonomy
 - comments
 - group_comments
 - photometry
 - group_photometry
 - spectra
 - followuprequests
 - thumbnails
 - observingruns
 - classicalassignments
[✓] Creating tables
    - acls
    - roles
    - role_acls
    - users
    - tokens
    - token_acls
    - user_roles
    - usersocialauths
    - nonces
    - associations
    - codes
    - partials
    - groups
    - group_users
    - streams
    - stream_groups
    - objs
    - filters
    - candidates
    - sources
    - sourceviews
    - telescopes
    - group_telescopes
    - instruments
    - taxonomies
    - group_taxonomy
    - comments
    - group_comments
    - photometry
    - group_photometry
    - spectra
    - followuprequests
    - thumbnails
    - observingruns
    - classicalassignments
[✓] Creating permissions
[✗] Creating users & sitewide public group
Traceback (most recent call last):
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "groups_name_key"
DETAIL:  Key (name)=(Sitewide Group) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/danny/PycharmProjects/skyportal/baselayer/app/model_util.py", line 16, in status
    yield
  File "tools/data_loader.py", line 65, in <module>
    DBSession().commit()
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1138, in _emit_insert_statements
    statement, params
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "groups_name_key"
DETAIL:  Key (name)=(Sitewide Group) already exists.

[SQL: INSERT INTO groups (created_at, modified, name, single_user_group) VALUES (now(), now(), %(name)s, %(single_user_group)s) RETURNING groups.id]
[parameters: {'name': 'Sitewide Group', 'single_user_group': False}]
(Background on this error at: http://sqlalche.me/e/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/data_loader.py", line 77, in <module>
    users_dict = {user.username: user.id for user in users}
  File "/anaconda2/envs/skyportal2/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/danny/PycharmProjects/skyportal/baselayer/app/model_util.py", line 23, in status
    models.DBSession().commit()
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 492, in commit
    self._assert_active(prepared_ok=True)
  File "/anaconda2/envs/skyportal2/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 295, in _assert_active
    code="7s2a",
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "groups_name_key"
DETAIL:  Key (name)=(Sitewide Group) already exists.

[SQL: INSERT INTO groups (created_at, modified, name, single_user_group) VALUES (now(), now(), %(name)s, %(single_user_group)s) RETURNING groups.id]
[parameters: {'name': 'Sitewide Group', 'single_user_group': False}]
(Background on this error at: http://sqlalche.me/e/gkpj) (Background on this error at: http://sqlalche.me/e/7s2a)
make: *** [load_seed_data] Error 1```

**Comment by profjsb** [comment]
Yes—these loaders are meant as the initial data establishment for a fresh SP instance. It doesn’t make sense to run multiple loaders on a single instance. We should document this better.
