### ISSUE TITLE
Missing `config.yaml` after initial clone; warn user appropriately

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#69]
After clean clone and `make`:

```
Traceback (most recent call last):
  File "baselayer/tools/env_summary.py", line 5, in <module>
    env, cfg = load_env()
  File "/tmp/skyportal/baselayer/app/env.py", line 28, in load_env
    cfg = load_config(config_files=env.config or [])
  File "/tmp/skyportal/baselayer/app/config.py", line 71, in load_config
    raise RuntimeError(f"[Baselayer] Missing config files: {missing}")
RuntimeError: [Baselayer] Missing config files: ['config.yaml']
make: *** [baselayer/Makefile:68: run] Error 1
```

Provide a sensible error message, telling the user to copy and customize `config.yaml.defaults`.

**Comment by stefanv** [comment]
Closed by #57.
